name: Materials
version: '${project.version}'
main: org.hg.materials.Materials
api-version: '1.18'
authors: [Filabdict]
commands:
  open_material_list:
    permission: op
  apply_material:
    permission: blacksmith
  view_apply_materials:
    permission: blacksmith
